### ISSUE TITLE
Allow clients to provide a default value

### ISSUE THREAD

**Issue by rwparris2** [Unleash/proxy-client-vue#26] opened 2023-12-18 21:41 UTC
### Describe the feature request

Vue users should be able provide a default value when using `useFlag`

e.g. the following options to should all be allowed

`useFlag('my-cool-flag')`  
`useFlag('my-cool-flag', true)`  
`useFlag('my-cool-flag', false)`

The behavior of a default value is outlined in the client specification document https://docs.getunleash.io/client-specification

**Comment by thomasheartman** [comment] 2023-12-19 14:38
Hy, @rwparris2! Thanks for the suggestion.

However, none of the Unleash front-end SDKs (aka client-side SDKs) allow you to send default values by design. The client spec is for server-side SDKs, specifically. Client-side SDKs work quite differently to avoid potential data leaks that might be caused by sending flag data to client-facing software.

Instead of evaluating their flags locally, client-side SDKs receive only a list of enabled flags. You can read more about this in the [docs on client-side SDK behavior](https://docs.getunleash.io/reference/sdks#client-side-sdk-behavior) and in the [second principle for building feature flag systems (the principle of least privilege)](https://docs.getunleash.io/topics/feature-flags/never-expose-pii).

So front-end SDKs only know about enabled flags. This means that a disabled flag and a missing flag are absolutely identical. The fallback values for server-side SDKs are intended to be used for missing flags, but a missing flag and a disabled flag are the same to front-end SDKs.

`useFlag('enabled', true)` would always be true and `useFlag('maybe', false)` would always give you the value of the flag regardless. So the extra parameter here doesn't provide any benefit. 

Does that sound reasonable to you? 

We've had the same request for other front-end SDKs previously and dismissed it for the same reason. So what I'll do is that I'll close this issue for now, but feel free to reopen it if you think that there is something we're missing that we'd get by implementing this and we'd be more than happy to hear you out ☺️

**Closed as completed by thomasheartman** 2023-12-19 14:38 UTC
Labels: enhancement
